name: PR Workflow
on:
  pull_request:
jobs:
  build:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      ## This clones and checks out.
      - name: Checkout branch
        uses: actions/checkout@v3
      ## Setup node and npm caching.
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          registry-url: https://npm.pkg.github.com
          scope: '@nciocpl'
      - run: npm ci
      - run: npm run lint
      - run: npm test
