name: PR Workflow
on:
  pull_request:
jobs:
  build:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      ## This clones and checks out.
      - name: Checkout branch
        uses: actions/checkout@v4
      ## Setup node and package caching.
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: https://npm.pkg.github.com
          scope: '@nciocpl'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm test
